name: Deploy Server
on:
    push:
        branches:
            - master
        tags-ignore:

jobs:
    create-release:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        name: "Deploy Package"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: ğŸ— Install dependencies
              run: npm i

            - name: "ğŸš¦ Build package"
              run: npm run build
            
            - name: "ğŸ“– Build Example"
              run: npm run deployExample

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm run release

            
