name: Deploy Server
on:
    push:
        branches:
            - master
        tags-ignore:

jobs:
    create-release:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        name: "Deploy Package"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: technote-space/auto-cancel-redundant-job@v1
            - name: ğŸ— Install dependencies
              run: npm i

            - name: "ğŸš¦ Build package"
              run: npm run build

            - name: "ğŸ“– Build Storybook"
              run: npm run build-storybook

            - name: ğŸš€ Deploy Storybook
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: example # The folder the action should deploy.
                  CLEAN: true

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm run release
